-- MySQL Script generated by MySQL Workbench
-- Sat Feb  8 22:09:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema onlineforumapplication
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `onlineforumapplication` ;

-- -----------------------------------------------------
-- Schema onlineforumapplication
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onlineforumapplication` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `onlineforumapplication` ;

-- -----------------------------------------------------
-- Table `onlineforumapplication`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineforumapplication`.`user` ;

CREATE TABLE IF NOT EXISTS `onlineforumapplication`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `facebook_id` VARCHAR(255) NULL DEFAULT NULL,
  `full_name` VARCHAR(50) NOT NULL,
  `is_active` BIT(1) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(10) NOT NULL,
  `registration_date` DATETIME(6) NULL DEFAULT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `user_role` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UKob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UKlqjrcobrh9jc8wpcar64q1bfh` (`user_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `onlineforumapplication`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineforumapplication`.`category` ;

CREATE TABLE IF NOT EXISTS `onlineforumapplication`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `FK4gee1gl2pvbutkm3b6l32mxg6` (`created_by` ASC) VISIBLE,
  CONSTRAINT `FK4gee1gl2pvbutkm3b6l32mxg6`
    FOREIGN KEY (`created_by`)
    REFERENCES `onlineforumapplication`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `onlineforumapplication`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineforumapplication`.`post` ;

CREATE TABLE IF NOT EXISTS `onlineforumapplication`.`post` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `is_active` BIT(1) NULL DEFAULT NULL,
  `post_date` DATETIME(6) NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `visibility` BIT(1) NULL DEFAULT NULL,
  `author_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `FK12njtf8e0jmyb45lqfpt6ad89` (`author_id` ASC) VISIBLE,
  INDEX `FKg6l1ydp1pwkmyj166teiuov1b` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FK12njtf8e0jmyb45lqfpt6ad89`
    FOREIGN KEY (`author_id`)
    REFERENCES `onlineforumapplication`.`user` (`user_id`),
  CONSTRAINT `FKg6l1ydp1pwkmyj166teiuov1b`
    FOREIGN KEY (`category_id`)
    REFERENCES `onlineforumapplication`.`category` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `onlineforumapplication`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineforumapplication`.`comment` ;

CREATE TABLE IF NOT EXISTS `onlineforumapplication`.`comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment_date` DATETIME(6) NULL DEFAULT NULL,
  `content` VARCHAR(255) NOT NULL,
  `is_active` BIT(1) NULL DEFAULT NULL,
  `author_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `FKh1gtv412u19wcbx22177xbkjp` (`author_id` ASC) VISIBLE,
  INDEX `FKs1slvnkuemjsq2kj4h3vhx7i1` (`post_id` ASC) VISIBLE,
  CONSTRAINT `FKh1gtv412u19wcbx22177xbkjp`
    FOREIGN KEY (`author_id`)
    REFERENCES `onlineforumapplication`.`user` (`user_id`),
  CONSTRAINT `FKs1slvnkuemjsq2kj4h3vhx7i1`
    FOREIGN KEY (`post_id`)
    REFERENCES `onlineforumapplication`.`post` (`post_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `onlineforumapplication`.`follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineforumapplication`.`follow` ;

CREATE TABLE IF NOT EXISTS `onlineforumapplication`.`follow` (
  `follow_id` INT NOT NULL AUTO_INCREMENT,
  `follow_date` DATETIME(6) NULL DEFAULT NULL,
  `followed_id` INT NOT NULL,
  `follower_id` INT NOT NULL,
  PRIMARY KEY (`follow_id`),
  INDEX `FK3gu03ktcbxq8nm9rf4ll2glrr` (`followed_id` ASC) VISIBLE,
  INDEX `FKmow2qk674plvwyb4wqln37svv` (`follower_id` ASC) VISIBLE,
  CONSTRAINT `FK3gu03ktcbxq8nm9rf4ll2glrr`
    FOREIGN KEY (`followed_id`)
    REFERENCES `onlineforumapplication`.`user` (`user_id`),
  CONSTRAINT `FKmow2qk674plvwyb4wqln37svv`
    FOREIGN KEY (`follower_id`)
    REFERENCES `onlineforumapplication`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `onlineforumapplication`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineforumapplication`.`media` ;

CREATE TABLE IF NOT EXISTS `onlineforumapplication`.`media` (
  `media_id` INT NOT NULL AUTO_INCREMENT,
  `file_type` BIT(1) NULL DEFAULT NULL,
  `fileurl` VARCHAR(255) NOT NULL,
  `upload_date` DATETIME(6) NULL DEFAULT NULL,
  `comment_id` INT NULL DEFAULT NULL,
  `post_id` INT NULL DEFAULT NULL,
  `uploaded_by_id` INT NOT NULL,
  PRIMARY KEY (`media_id`),
  INDEX `FKpo2buh2muj0nd20xop2n2ag7s` (`comment_id` ASC) VISIBLE,
  INDEX `FKa53unad5f5hkapdfirbscm8n6` (`post_id` ASC) VISIBLE,
  INDEX `FKnrsx96hoosqv9qfb4gaih44kk` (`uploaded_by_id` ASC) VISIBLE,
  CONSTRAINT `FKa53unad5f5hkapdfirbscm8n6`
    FOREIGN KEY (`post_id`)
    REFERENCES `onlineforumapplication`.`post` (`post_id`),
  CONSTRAINT `FKnrsx96hoosqv9qfb4gaih44kk`
    FOREIGN KEY (`uploaded_by_id`)
    REFERENCES `onlineforumapplication`.`user` (`user_id`),
  CONSTRAINT `FKpo2buh2muj0nd20xop2n2ag7s`
    FOREIGN KEY (`comment_id`)
    REFERENCES `onlineforumapplication`.`comment` (`comment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `onlineforumapplication`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineforumapplication`.`message` ;

CREATE TABLE IF NOT EXISTS `onlineforumapplication`.`message` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `is_read` BIT(1) NULL DEFAULT NULL,
  `sent_date` DATETIME(6) NULL DEFAULT NULL,
  `receiver_id` INT NOT NULL,
  `senderid` INT NOT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `FK86f0kc2mt26ifwupnivu6v8oa` (`receiver_id` ASC) VISIBLE,
  INDEX `FK9rsnsv6vny3iki4e53h6biv5e` (`senderid` ASC) VISIBLE,
  CONSTRAINT `FK86f0kc2mt26ifwupnivu6v8oa`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `onlineforumapplication`.`user` (`user_id`),
  CONSTRAINT `FK9rsnsv6vny3iki4e53h6biv5e`
    FOREIGN KEY (`senderid`)
    REFERENCES `onlineforumapplication`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
