spring:
  application:
    name: forum
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlineforumapplication
    username: root
    password: 252525!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update